name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - name: Create .nojekyll file
        run: |
          if [ -d "public" ]; then
            touch public/.nojekyll
          else
            echo "Public directory not found"
            exit 1
          fi
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public