name: Deploy to GitHub Pages
on:
  push:
    branches: 'main'
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Debug - Show package.json
        run: cat package.json
      
      - name: Install dependencies
        run: npm install
      
      - name: Debug - List files before build
        run: ls -la
      
      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build
      
      - name: Debug - List files after build
        run: |
          echo "Root directory:"
          ls -la
          echo "Possible build directories:"
          [ -d "build" ] && echo "build directory exists" && ls -la build || echo "No build directory"
          [ -d "dist" ] && echo "dist directory exists" && ls -la dist || echo "No dist directory"
          [ -d "public" ] && echo "public directory exists" && ls -la public || echo "No public directory"
          [ -d "out" ] && echo "out directory exists" && ls -la out || echo "No out directory"
          [ -d ".next" ] && echo ".next directory exists" && ls -la .next || echo "No .next directory"
      
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # This will be dynamically determined after seeing debug output
          path: 'build/'
  
  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4